[build]
  command = "yarn build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://cecilianarchive.com/*"
  to = "https://www.cecilianarchives.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.cecilianarchive.com/*"
  to = "https://www.cecilianarchives.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://upload.cecilianarchives.com/*"
  to = "https://www.cecilianarchives.com/:splat"
  status = 301
  force = true
